### ISSUE TITLE
Add table of comparison with nodegit.org

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [SamyPesse/gitkit-js#11]
What is the effective difference between this and [NodeGit](http://www.nodegit.org/)? Maybe the fact it runs in the browser? Can we have a table of comparison between both in the README so that we can understand what are the differences and adapt to our use cases?

Thanks.

**Comment by jschr** [comment]
Would also love some context as to why this library was created (in a good way). I'm currently using NodeGit + Electron and having to build native modules for the different platforms has been a major pain. If this library can be used as a replacement that would be awesome! Also being able to use it in a Chrome packaged app is a major win as well.

**Comment by FagnerMartinsBrack** [comment]
It seems the main difference is that this uses native JavaScript while nodegit is just a wrapper on top of git native library. I wonder if that's a benefit though, since using native libraries is supposed to be faster...

**Comment by SamyPesse** [comment]
GitKit is an experiment and its main purpose is to learn more about Git internals while providing an easy to use **pure-JavaScript** and clean implementation of Git.
It'll never be as good as Nodegit which is a binding of `libgit2`.

**If you can use Nodegit, you should use Nodegit!**

But if you want to use Git in a browser application (ex: Chrome packaged app), then feel free to contribute to GitKit 🍻

**Comment by FagnerMartinsBrack** [comment]
> But if you want to use Git in a browser application (ex: Chrome packaged app), then feel free to contribute to GitKit 🍻

It is a very good you can use in the browser, although someone must come up with a smart use case xD

@SamyPesse Thanks for answering 👍
