### ISSUE TITLE
Remove requirement for git for installation

### ISSUE THREAD

**Issue by rjmunro** [SamyPesse/gitkit-js#6]
It looks like this requires a command line git before it can be installed because when I try to install this in a container on https://hyperdev.com/, I get the following in error logs:

```
 ERR! git clone --template=/app/.npm/_git-remotes/_templates --mirror git@github.com:deoxxa/dissolve.git /app/.npm/_git-remotes/git-github-com-deoxxa-dissolve-git-4ec7095e: undefined
npm ERR! git clone --template=/app/.npm/_git-remotes/_templates --mirror git@github.com:deoxxa/dissolve.git /app/.npm/_git-remotes/git-github-com-deoxxa-dissolve-git-4ec7095e: undefined
 ERR! Linux 4.4.8-fc
npm ERR! argv "/app/.nodejs/bin/node" "/app/.nodejs/bin/npm" "install"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
 ERR! code ENOGIT

npm ERR! not found: git
npm ERR!
 
npm 
ERR! Failed using git.
npm 
ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

```

**Comment by SamyPesse** [comment]
GitKit is still using a fork of `dissolve`, waiting for https://github.com/deoxxa/dissolve/pull/20 to be merged.

**Comment by rjmunro** [comment]
Thanks.

I had assumed it wanted it because it's a git related project not because npm needs it to install a dependency, but now I realise this is more hyperdev's problem than gitkits - it applies to any non-npm dependency.

I've reported the issue on their support, and they've said they'll look at it:
http://support.hyperweb.space/t/install-package-json-dependency-from-git-not-npm/388/2
